/* ==========================================================================
   omnibus.mjs  -  several books, bound as one
   --------------------------------------------------------------------------
   An omnibus is a book whose pages are other books' pages. Nothing in it is
   written twice: this reads the books named in books/<slug>/omnibus.json and
   writes the omnibus's sources from theirs, so a page fixed in its own book is
   fixed in the omnibus the next time this runs.

   Usage:
       node engine/tools/omnibus.mjs books/<slug>
       node engine/tools/build.mjs   books/<slug>        then the loop, as ever

   Reads:   books/<slug>/omnibus.json     which books, in what order
            books/<slug>/book.json        the omnibus's own title, cover, listing
            books/<from>/…                each source book, untouched
   Writes:  books/<slug>/<slug>.html      every page, byte for byte as its book has it
            books/<slug>/FACTS.md         every fact, renumbered so no two books collide
            books/<slug>/blocks.md        every plan entry, citing the renumbered facts
            books/<slug>/GLOSSARY.md      every term
            books/<slug>/book.json        "parts" only, and the guide page if asked for

   omnibus.json:
       {
         "guide": "Three Books in One",
         "books": [
           { "from": "power-bi-beginner", "label": "Book One" },
           { "from": "power-bi-dax",      "label": "Book Two" }
         ]
       }

   "label" goes in front of every part's eyebrow, so a divider says which book
   the reader is in. "guide" is optional: the title of a front matter page
   listing the books, each with its subtitle and the parts and lessons it
   covers. It is made from the books' own titles, so there is nothing to write.
   A prose page the books share by name in their back matter (an "Answers"
   page) is carried over as one page holding every book's text in order. The
   rest of the omnibus's matter is its own, written in its book.json.

   A fact keeps its number and gains its book: F17 in the second book is F2017.

   Pages are copied whole, so a page's content hash is the same here as in its
   own book. The omnibus keeps its own review record, workflow.json, and a
   person signs it off in the Studio like any other book. --carry-approvals,
   on the author's say-so, copies each source book's approval across for every
   page whose content is still exactly what was approved there, with the date
   and note it was given. A page edited since, or never approved, stays as it
   is here.

   The four generated files carry a marker on their first lines. This refuses
   to overwrite one that does not, so it can never eat a file written by hand.
   ========================================================================== */
import fs from 'node:fs';
import path from 'node:path';
import { BOOKS, SLUG_RE, loadBook, loadWorkflow, saveWorkflow, statusOf } from './lib/book.mjs';

const argv = process.argv.slice(2);
const bookDir = argv.find((a) => !a.startsWith('--'));
if (!bookDir) {
  console.error('Usage: node engine/tools/omnibus.mjs books/<slug> [--carry-approvals]');
  process.exit(1);
}
const carry = argv.includes('--carry-approvals');
const die = (msg) => { console.error('\n' + msg + '\n'); process.exit(1); };
const dir = path.resolve(bookDir);
const slug = path.basename(dir);

const cfgPath = path.join(dir, 'omnibus.json');
if (!fs.existsSync(cfgPath)) die(`No omnibus.json in ${bookDir}. It names the books to bind: see the top of engine/tools/omnibus.mjs.`);
if (!fs.existsSync(path.join(dir, 'book.json'))) die(`No book.json in ${bookDir}. The omnibus needs its own title, author and cover; "parts" can start as [].`);
let cfg;
try { cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8')); }
catch (e) { die(`omnibus.json is not valid JSON:\n  ${e.message}`); }
if (!Array.isArray(cfg.books) || !cfg.books.length) die('omnibus.json needs a "books" array, one { "from": "<slug>", "label": "Book One" } per book.');

const MARK = 'GENERATED by engine/tools/omnibus.mjs';
const noComments = (s) => s.replace(/<!--[\s\S]*?-->/g, (m) => m.replace(/[^\n]/g, ' '));

/* ------------------------------------------------------------- 1. the sources */
const sources = cfg.books.map((b, k) => {
  if (!b || !SLUG_RE.test(b.from || '')) die(`omnibus.json books[${k}]: "from" should be a book's folder name.`);
  if (b.from === slug) die(`omnibus.json books[${k}]: an omnibus cannot include itself.`);
  const from = path.join(BOOKS, b.from);
  if (!fs.existsSync(path.join(from, 'book.json'))) die(`omnibus.json books[${k}]: there is no book at books/${b.from}.`);
  if (fs.existsSync(path.join(from, 'omnibus.json'))) die(`omnibus.json books[${k}]: books/${b.from} is itself an omnibus. Name its books here instead.`);
  const book = loadBook(from);
  if (book.missing.length) die(`books/${b.from} lists pages that are not written:\n` + book.missing.map((t) => `  - ${t}`).join('\n'));
  const byTitle = new Map(book.pages.map((p) => [p.title, p]));
  return { ...b, n: k + 1, label: String(b.label || `Book ${k + 1}`), book, pages: book.ordered.map((t) => byTitle.get(t)) };
});

const all = sources.flatMap((s) => s.pages.map((p) => ({ ...p, from: s.from })));
const seen = new Map();
for (const p of all) {
  if (seen.has(p.title)) die(`Two books both have a page titled "${p.title}" (${seen.get(p.title)} and ${p.from}). Titles have to be unique in one book: rename one.`);
  seen.set(p.title, p.from);
}
const withImages = all.filter((p) => /(?:src|href)="images\//.test(p.html));
if (withImages.length) die('These pages show a picture from their own book\'s images/ folder, and an omnibus does not carry pictures across yet:\n' +
  withImages.map((p) => `  - ${p.title} (${p.from})`).join('\n'));

/* One document, one namespace: two SVG definitions sharing an id is harmless while they
   are the same, and silently wrong the moment they differ (the first one wins). */
const json = JSON.parse(fs.readFileSync(path.join(dir, 'book.json'), 'utf8'));
const DEF = /<(filter|linearGradient|radialGradient|marker|clipPath|pattern|mask|symbol)\b[^>]*\bid="([^"]+)"[\s\S]*?<\/\1>/g;
const defs = new Map();
for (const p of [{ title: 'the cover art in book.json', html: json.cover?.art || '' }, ...all])
  for (const m of p.html.matchAll(DEF)) {
    const versions = defs.get(m[2]) || defs.set(m[2], new Map()).get(m[2]);
    const key = m[0].replace(/\s+/g, ' ');
    versions.set(key, [...(versions.get(key) || []), p.title]);
  }
const clashes = [...defs].filter(([, versions]) => versions.size > 1);
if (clashes.length) die('These SVG ids are defined differently on different pages. In one book the first definition wins for all of them, so a diagram would be drawn with another page\'s filter. Give each its own id:\n' +
  clashes.map(([id, versions]) => `  - #${id}: ${[...versions.values()].map((t) => t[0]).join(' / ')}`).join('\n'));

/* ------------------------------------------------------------- 2. the interior */
const first = sources[0].book;
const bareHead = (h) => h.replace(/<!--[\s\S]*?-->\s*/g, '').replace(/<title>[\s\S]*?<\/title>/, '');
for (const s of sources.slice(1))
  if (bareHead(s.book.head) !== bareHead(first.head))
    console.log(`note: books/${s.from} has a different <head> from books/${sources[0].from}. The omnibus uses the first book's.`);

const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const header = `<!doctype html>
<!--
  ${MARK}. Do not edit this file.

  Every page here is copied, whole, from the book it belongs to:
${sources.map((s) => `    ${s.label}: books/${s.from}/${path.basename(s.book.interiorPath)}`).join('\n')}

  To change a page, change it in its own book, then run:

    node engine/tools/omnibus.mjs books/${slug}
    node engine/tools/build.mjs   books/${slug}

  To change which books are in here, or their order, edit omnibus.json.
-->
`;
const interior = header +
  first.head.replace(/<!--[\s\S]*?-->\s*/g, '').replace(/^\s*<!doctype html>\s*/i, '')
    .replace(/<title>[\s\S]*?<\/title>/, `<title>${esc(json.title || slug)}</title>`).replace(/\s+$/, '') + '\n\n' +
  sources.map((s) => `    <!-- ===== ${s.label}: ${s.book.json.title || s.from} (books/${s.from}) ===== -->\n\n` +
    s.pages.map((p) => '    ' + p.html).join('\n\n')).join('\n\n') +
  first.tail;

/* ------------------------------------------------------------- 3. facts and plan */
const factId = (s, id) => `F${s.n * 1000 + Number(id.slice(1))}`;
const read = (s, name) => { const f = path.join(s.book.dir, name); return fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : ''; };
const tidy = (block) => block.replace(/(?:\s*\n-{3,}[ \t]*)+\s*$/, '').replace(/\s+$/, '');
/* cut a markdown file at its headings, found with comments blanked so a commented-out
   example is never taken for the real thing */
const sections = (md, re) => {
  const heads = [...noComments(md).matchAll(re)];
  return heads.map((h, i) => ({ m: h, text: md.slice(h.index, i + 1 < heads.length ? heads[i + 1].index : md.length) }));
};

let factCount = 0;
const facts = sources.map((s) => {
  const own = sections(read(s, 'FACTS.md'), /^##\s+(F\d+)\b.*$/gim);
  if (own.some(({ m }) => Number(m[1].slice(1)) > 999)) die(`books/${s.from}/FACTS.md has a fact numbered past F999, and the omnibus numbers a book's facts in thousands.`);
  factCount += own.length;
  return `<!-- ===== ${s.label}: books/${s.from}/FACTS.md ===== -->\n\n` +
    own.map(({ m, text }) => tidy(text.replace(m[1], factId(s, m[1].toUpperCase())))).join('\n\n---\n\n');
}).join('\n\n---\n\n');
const factsMd = `<!-- ${MARK}. Do not edit: change a fact in its own book, then run omnibus.mjs again. -->
# Facts

Every fact from the books in this omnibus, each exactly as its own book records it. A
fact keeps its number and gains its book: F17 in the second book is F2017 here.

---

${facts}
`;

let partNo = 0;
const plan = sources.map((s) => {
  const md = read(s, 'blocks.md');
  const start = noComments(md).search(/^##\s+/m);
  if (start === -1) return '';
  const body = md.slice(start)
    .replace(/(\*\*Facts:\*\*)([\s\S]*?)(?=\n\s*-\s+\*\*|\n\s*\n|\n\s*-{3,}|\n#|$)/g,
      (m, name, ids) => name + ids.replace(/\bF\d+\b/gi, (id) => factId(s, id.toUpperCase())));
  const scan = noComments(body);
  let out = '', at = 0;
  for (const h of scan.matchAll(/^##\s+(.+)$/gm)) {
    const name = h[1].replace(/^Part\s+\d+\s*[·:.\-]\s*/i, '').trim();
    out += body.slice(at, h.index) + `## Part ${++partNo} · ${name}`;
    at = h.index + h[0].length;
  }
  return `<!-- ===== ${s.label}: books/${s.from}/blocks.md ===== -->\n\n` + tidy(out + body.slice(at));
}).filter(Boolean).join('\n\n---\n\n');
const blocksMd = `<!-- ${MARK}. Do not edit: change an entry in its own book, then run omnibus.mjs again. -->
# Blocks

The plan for every page in this omnibus, each entry exactly as its own book has it, with
its facts renumbered to match FACTS.md here.

---

${plan}
`;

const terms = new Map();
for (const s of sources)
  for (const { m, text } of sections(read(s, 'GLOSSARY.md'), /^##\s+(.+?)\s*$/gm)) {
    const key = m[1].trim().toLowerCase();
    if (!terms.has(key)) terms.set(key, tidy(text));
    else if (terms.get(key).replace(/\s+/g, ' ') !== tidy(text).replace(/\s+/g, ' '))
      console.log(`note: "${m[1].trim()}" is defined differently in books/${s.from}/GLOSSARY.md. The omnibus keeps the first book's meaning.`);
  }
const glossaryMd = `<!-- ${MARK}. Do not edit: change a term in its own book, then run omnibus.mjs again. -->
# Glossary

Every term from the books in this omnibus. Where two books define the same word, the
first book's meaning is kept.

---
${[...terms.values()].map((t) => '\n' + t + '\n').join('')}`;

/* ------------------------------------------------------------- 4. the running order */
const parts = [], guideItems = [];
const span = (a, b, one, many) => (a === b ? `${one} ${a}` : `${many} ${a} to ${b}`);
let lesson = 0;
for (const s of sources) {
  const firstPart = parts.length + 1, firstLesson = lesson + 1;
  for (const p of s.book.json.parts.filter((p) => (p.blocks || []).length)) {
    parts.push({ ...p, eyebrow: [s.label, p.eyebrow].filter(Boolean).join(' · ') });
    lesson += p.blocks.length;
  }
  guideItems.push({
    name: `${s.label} · ${s.book.json.title || s.from}`,
    note: [s.book.json.subtitle, `${span(firstPart, parts.length, 'Part', 'Parts')}, ${span(firstLesson, lesson, 'lesson', 'lessons')}.`].filter(Boolean).join(' '),
  });
}

const nextJson = { ...json, parts };

/* Back matter the books share by name (an "Answers" page, say) is carried over as one
   page, the books' bodies one after another in reading order. Front matter is the
   omnibus's own: the books' prefaces do not add up to one. */
const shared = new Map();
for (const s of sources)
  for (const m of s.book.json.matter?.back || [])
    if (m && m.kind === 'prose' && m.title) shared.set(m.title, [...(shared.get(m.title) || []), ...(Array.isArray(m.body) ? m.body : [String(m.body || '')])]);
if (shared.size) {
  const back = [...(json.matter?.back || [])];
  for (const [title, body] of shared) {
    const i = back.findIndex((m) => m && m.kind === 'prose' && m.title === title);
    if (i === -1) back.unshift({ kind: 'prose', title, body }); else back[i] = { ...back[i], body };
  }
  nextJson.matter = { ...(nextJson.matter || {}), back };
}
if (cfg.guide) {
  const page = { kind: 'list', title: String(cfg.guide), items: guideItems };
  const front = [...(json.matter?.front || [])];
  const i = front.findIndex((m) => m && m.kind === 'list' && m.title === page.title);
  if (i === -1) front.unshift(page); else front[i] = { ...front[i], items: guideItems };
  nextJson.matter = { ...(nextJson.matter || {}), front };
}

/* ------------------------------------------------------------- 5. write, only what changed */
const wrote = [];
const put = (name, text, generated = true) => {
  const f = path.join(dir, name);
  const old = fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : null;
  if (generated && old !== null && !old.slice(0, 400).includes(MARK))
    die(`${path.relative(process.cwd(), f)} was not written by this tool, so it was left alone and nothing was changed.\nMove it out of the way if the omnibus should replace it.`);
  return () => { if (old !== text) { fs.writeFileSync(f, text); wrote.push(name); } };
};
/* every refusal happens before the first write, so a run never leaves half an omnibus */
const writes = [
  put(json.interior || `${slug}.html`, interior),
  put('FACTS.md', factsMd), put('blocks.md', blocksMd), put('GLOSSARY.md', glossaryMd),
  put('book.json', JSON.stringify(nextJson, null, 2) + '\n', false),
];
for (const w of writes) w();

const wf = loadWorkflow(dir);
let signed = 0, carried = 0;
for (const s of sources) {
  const their = loadWorkflow(s.book.dir);
  for (const p of s.pages) {
    if (statusOf(p, their).status !== 'approved') continue;   // approved there, and not edited since
    signed++;
    if (!carry || statusOf(p, wf).status === 'approved') continue;
    wf.pages[p.title] = { ...their.pages[p.title], hash: p.hash };
    carried++;
  }
}
if (carried) saveWorkflow(dir, wf);
const here = all.filter((p) => statusOf(p, wf).status === 'approved').length;

const rel = path.relative(process.cwd(), dir).replace(/\\/g, '/');
console.log(`bound ${sources.length} books into ${rel}: ${all.length} pages in ${parts.length} parts, ${factCount} facts, ${terms.size} glossary term${terms.size === 1 ? '' : 's'}`);
for (const s of sources) console.log(`  ${s.label}: ${s.book.json.title || s.from}, ${s.pages.length} pages`);
console.log(wrote.length ? `  wrote ${wrote.join(', ')}` : '  nothing changed');
console.log(`  review: ${signed} of ${all.length} pages are approved in their own books, ${here} in this one${carried ? ` (${carried} carried over)` : ''}. It keeps its own record.`);
console.log(`\nNext: node engine/tools/build.mjs ${rel}`);
